<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_account.city</name>
   <tag></tag>
   <elementGuidId>e4c48633-a038-4f72-84d4-92f389299b7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='account.city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;account.city&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;account\.city&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46cfc063-ebc4-4a52-88a6-1ab3dd3101a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account.city</value>
      <webElementGuid>5c236e0f-273f-4b23-8bc0-8150ad7f673b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d76fae9-21eb-49af-93a1-1f3eb2f4224a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[2]/tbody[1]/tr[7]/td[2]/input[1]</value>
      <webElementGuid>9ddf24e5-7437-4bcc-864c-9f5d5aaca502</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='account.city']</value>
      <webElementGuid>6023e878-0c71-434e-a6da-d01cf8b242ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table[2]/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>068c6257-1227-4b57-8a36-5468af588df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>e9bbae92-82d5-414a-a95e-f49a8822a0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'account.city' and @type = 'text']</value>
      <webElementGuid>cc46092b-b5a3-41a3-94f6-78d4e431ccac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
