<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_HTTP Status 500  Internal Server Error_b41525</name>
   <tag></tag>
   <elementGuidId>38498750-2364-4661-ad5b-5e3cc6ed126b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;HTTP Status 500 – Internal Server ErrorType Exception ReportMessage Unhandled ex&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>35f2b750-5b65-4353-a400-15ef0a6e7113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HTTP Status 500 – Internal Server ErrorType Exception ReportMessage Unhandled exception in exception handler.Description The server encountered an unexpected condition that prevented it from fulfilling the request.Exceptionnet.sourceforge.stripes.exception.StripesServletException: Unhandled exception in exception handler.
	net.sourceforge.stripes.exception.DefaultExceptionHandler.handle(DefaultExceptionHandler.java:179)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:263)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Root Causeorg.springframework.dao.DuplicateKeyException: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
### The error may exist in org/mybatis/jpetstore/mapper/AccountMapper.xml
### The error may involve org.mybatis.jpetstore.mapper.AccountMapper.insertAccount-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO ACCOUNT       (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)     VALUES       (?, ?, ?, ?, ?,  ?, ?, ?, ?, ?, ?, ?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
; integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT; nested exception is java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
	org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:244)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
	jdk.proxy3/jdk.proxy3.$Proxy15.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	jdk.proxy3/jdk.proxy3.$Proxy17.insertAccount(Unknown Source)
	org.mybatis.jpetstore.service.AccountService.insertAccount(AccountService.java:55)
	org.mybatis.jpetstore.service.AccountService$$FastClassBySpringCGLIB$$620cdb68.invoke(&lt;generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	org.mybatis.jpetstore.service.AccountService$$EnhancerBySpringCGLIB$$8f9537be.insertAccount(&lt;generated>)
	org.mybatis.jpetstore.web.actions.AccountActionBean.newAccount(AccountActionBean.java:116)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:176)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Root Causejava.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
	org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
	org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:48)
	org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:75)
	org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	jdk.proxy3/jdk.proxy3.$Proxy15.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	jdk.proxy3/jdk.proxy3.$Proxy17.insertAccount(Unknown Source)
	org.mybatis.jpetstore.service.AccountService.insertAccount(AccountService.java:55)
	org.mybatis.jpetstore.service.AccountService$$FastClassBySpringCGLIB$$620cdb68.invoke(&lt;generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	org.mybatis.jpetstore.service.AccountService$$EnhancerBySpringCGLIB$$8f9537be.insertAccount(&lt;generated>)
	org.mybatis.jpetstore.web.actions.AccountActionBean.newAccount(AccountActionBean.java:116)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:176)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Root Causeorg.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
	org.hsqldb.error.Error.error(Unknown Source)
	org.hsqldb.Constraint.getException(Unknown Source)
	org.hsqldb.index.IndexAVL.insert(Unknown Source)
	org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
	org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
	org.hsqldb.Session.addInsertAction(Unknown Source)
	org.hsqldb.Table.insertSingleRow(Unknown Source)
	org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
	org.hsqldb.StatementInsert.getResult(Unknown Source)
	org.hsqldb.StatementDMQL.execute(Unknown Source)
	org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	org.hsqldb.Session.execute(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
	org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:48)
	org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:75)
	org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	jdk.proxy3/jdk.proxy3.$Proxy15.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	jdk.proxy3/jdk.proxy3.$Proxy17.insertAccount(Unknown Source)
	org.mybatis.jpetstore.service.AccountService.insertAccount(AccountService.java:55)
	org.mybatis.jpetstore.service.AccountService$$FastClassBySpringCGLIB$$620cdb68.invoke(&lt;generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	org.mybatis.jpetstore.service.AccountService$$EnhancerBySpringCGLIB$$8f9537be.insertAccount(&lt;generated>)
	org.mybatis.jpetstore.web.actions.AccountActionBean.newAccount(AccountActionBean.java:116)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:176)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Note The full stack trace of the root cause is available in the server logs.Apache Tomcat/9.0.87/html[1]/body[1]</value>
      <webElementGuid>60217a4b-0e01-4d26-88a3-eb1495813576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>fdc76726-0e33-4f5d-81d2-177b5cde1955</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>9e143904-867f-4755-8b85-b09e1458bbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'HTTP Status 500 – Internal Server ErrorType Exception ReportMessage Unhandled exception in exception handler.Description The server encountered an unexpected condition that prevented it from fulfilling the request.Exceptionnet.sourceforge.stripes.exception.StripesServletException: Unhandled exception in exception handler.
	net.sourceforge.stripes.exception.DefaultExceptionHandler.handle(DefaultExceptionHandler.java:179)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:263)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Root Causeorg.springframework.dao.DuplicateKeyException: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
### The error may exist in org/mybatis/jpetstore/mapper/AccountMapper.xml
### The error may involve org.mybatis.jpetstore.mapper.AccountMapper.insertAccount-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO ACCOUNT       (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)     VALUES       (?, ?, ?, ?, ?,  ?, ?, ?, ?, ?, ?, ?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
; integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT; nested exception is java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
	org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:244)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
	jdk.proxy3/jdk.proxy3.$Proxy15.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	jdk.proxy3/jdk.proxy3.$Proxy17.insertAccount(Unknown Source)
	org.mybatis.jpetstore.service.AccountService.insertAccount(AccountService.java:55)
	org.mybatis.jpetstore.service.AccountService$$FastClassBySpringCGLIB$$620cdb68.invoke(&lt;generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	org.mybatis.jpetstore.service.AccountService$$EnhancerBySpringCGLIB$$8f9537be.insertAccount(&lt;generated>)
	org.mybatis.jpetstore.web.actions.AccountActionBean.newAccount(AccountActionBean.java:116)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:176)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Root Causejava.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
	org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
	org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:48)
	org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:75)
	org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	jdk.proxy3/jdk.proxy3.$Proxy15.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	jdk.proxy3/jdk.proxy3.$Proxy17.insertAccount(Unknown Source)
	org.mybatis.jpetstore.service.AccountService.insertAccount(AccountService.java:55)
	org.mybatis.jpetstore.service.AccountService$$FastClassBySpringCGLIB$$620cdb68.invoke(&lt;generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	org.mybatis.jpetstore.service.AccountService$$EnhancerBySpringCGLIB$$8f9537be.insertAccount(&lt;generated>)
	org.mybatis.jpetstore.web.actions.AccountActionBean.newAccount(AccountActionBean.java:116)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:176)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Root Causeorg.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
	org.hsqldb.error.Error.error(Unknown Source)
	org.hsqldb.Constraint.getException(Unknown Source)
	org.hsqldb.index.IndexAVL.insert(Unknown Source)
	org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
	org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
	org.hsqldb.Session.addInsertAction(Unknown Source)
	org.hsqldb.Table.insertSingleRow(Unknown Source)
	org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
	org.hsqldb.StatementInsert.getResult(Unknown Source)
	org.hsqldb.StatementDMQL.execute(Unknown Source)
	org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	org.hsqldb.Session.execute(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
	org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:48)
	org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:75)
	org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	jdk.proxy3/jdk.proxy3.$Proxy15.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	jdk.proxy3/jdk.proxy3.$Proxy17.insertAccount(Unknown Source)
	org.mybatis.jpetstore.service.AccountService.insertAccount(AccountService.java:55)
	org.mybatis.jpetstore.service.AccountService$$FastClassBySpringCGLIB$$620cdb68.invoke(&lt;generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	org.mybatis.jpetstore.service.AccountService$$EnhancerBySpringCGLIB$$8f9537be.insertAccount(&lt;generated>)
	org.mybatis.jpetstore.web.actions.AccountActionBean.newAccount(AccountActionBean.java:116)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:176)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Note The full stack trace of the root cause is available in the server logs.Apache Tomcat/9.0.87/html[1]/body[1]' or . = 'HTTP Status 500 – Internal Server ErrorType Exception ReportMessage Unhandled exception in exception handler.Description The server encountered an unexpected condition that prevented it from fulfilling the request.Exceptionnet.sourceforge.stripes.exception.StripesServletException: Unhandled exception in exception handler.
	net.sourceforge.stripes.exception.DefaultExceptionHandler.handle(DefaultExceptionHandler.java:179)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:263)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Root Causeorg.springframework.dao.DuplicateKeyException: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
### The error may exist in org/mybatis/jpetstore/mapper/AccountMapper.xml
### The error may involve org.mybatis.jpetstore.mapper.AccountMapper.insertAccount-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO ACCOUNT       (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)     VALUES       (?, ?, ?, ?, ?,  ?, ?, ?, ?, ?, ?, ?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
; integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT; nested exception is java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
	org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:244)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
	jdk.proxy3/jdk.proxy3.$Proxy15.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	jdk.proxy3/jdk.proxy3.$Proxy17.insertAccount(Unknown Source)
	org.mybatis.jpetstore.service.AccountService.insertAccount(AccountService.java:55)
	org.mybatis.jpetstore.service.AccountService$$FastClassBySpringCGLIB$$620cdb68.invoke(&lt;generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	org.mybatis.jpetstore.service.AccountService$$EnhancerBySpringCGLIB$$8f9537be.insertAccount(&lt;generated>)
	org.mybatis.jpetstore.web.actions.AccountActionBean.newAccount(AccountActionBean.java:116)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:176)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Root Causejava.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
	org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
	org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:48)
	org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:75)
	org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	jdk.proxy3/jdk.proxy3.$Proxy15.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	jdk.proxy3/jdk.proxy3.$Proxy17.insertAccount(Unknown Source)
	org.mybatis.jpetstore.service.AccountService.insertAccount(AccountService.java:55)
	org.mybatis.jpetstore.service.AccountService$$FastClassBySpringCGLIB$$620cdb68.invoke(&lt;generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	org.mybatis.jpetstore.service.AccountService$$EnhancerBySpringCGLIB$$8f9537be.insertAccount(&lt;generated>)
	org.mybatis.jpetstore.web.actions.AccountActionBean.newAccount(AccountActionBean.java:116)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:176)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Root Causeorg.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation ; PK_ACCOUNT table: ACCOUNT
	org.hsqldb.error.Error.error(Unknown Source)
	org.hsqldb.Constraint.getException(Unknown Source)
	org.hsqldb.index.IndexAVL.insert(Unknown Source)
	org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
	org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
	org.hsqldb.Session.addInsertAction(Unknown Source)
	org.hsqldb.Table.insertSingleRow(Unknown Source)
	org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
	org.hsqldb.StatementInsert.getResult(Unknown Source)
	org.hsqldb.StatementDMQL.execute(Unknown Source)
	org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	org.hsqldb.Session.execute(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
	org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:48)
	org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:75)
	org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	jdk.proxy3/jdk.proxy3.$Proxy15.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	jdk.proxy3/jdk.proxy3.$Proxy17.insertAccount(Unknown Source)
	org.mybatis.jpetstore.service.AccountService.insertAccount(AccountService.java:55)
	org.mybatis.jpetstore.service.AccountService$$FastClassBySpringCGLIB$$620cdb68.invoke(&lt;generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	org.mybatis.jpetstore.service.AccountService$$EnhancerBySpringCGLIB$$8f9537be.insertAccount(&lt;generated>)
	org.mybatis.jpetstore.web.actions.AccountActionBean.newAccount(AccountActionBean.java:116)
	java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	java.base/java.lang.reflect.Method.invoke(Method.java:580)
	net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:176)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
Note The full stack trace of the root cause is available in the server logs.Apache Tomcat/9.0.87/html[1]/body[1]')]</value>
      <webElementGuid>65cfe481-018c-4f75-bd7b-a38606e2373a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
