<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>22a459e8-46f5-4602-82ab-a8a43808d3c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SidebarContent > a:nth-of-type(2) > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SidebarContent']/a[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SidebarContent >> internal:role=link >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c3cb64b0-1656-4b2a-9fd5-8d963173f0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/dogs_icon.gif</value>
      <webElementGuid>08628276-3c5f-45f0-ba59-1ef364f120a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SidebarContent&quot;)/a[2]/img[1]</value>
      <webElementGuid>4fd384ed-bc28-452c-a9c7-a854e10a4028</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SidebarContent']/a[2]/img</value>
      <webElementGuid>0b7c1601-aa2d-4ddd-aab2-cb51b864c639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[2]/img</value>
      <webElementGuid>2006c220-c69d-4a12-9cc6-50687a219c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/dogs_icon.gif']</value>
      <webElementGuid>bd287b25-0df6-4f45-887a-4dd20138dc49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
