<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_K9-PO-02</name>
   <tag></tag>
   <elementGuidId>0b4e3067-cb66-4d01-a6bd-cb277ddaa2c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Catalog']/table/tbody/tr[3]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;K9-PO-02&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e2ffa258-2f97-46e0-a5d5-350367cf75f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/actions/Catalog.action?viewProduct=&amp;productId=K9-PO-02</value>
      <webElementGuid>65c9db61-ced2-4914-9c82-59f17639141d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>K9-PO-02</value>
      <webElementGuid>74aca53d-c91d-4420-8da2-a7e5f7fad418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/table[1]/tbody[1]/tr[3]/td[1]/a[1]</value>
      <webElementGuid>b65af31f-0670-4062-beb4-5c18880689f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/table/tbody/tr[3]/td/a</value>
      <webElementGuid>2b5755ce-36d5-47ff-bf61-bef0f7388672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'K9-PO-02')]</value>
      <webElementGuid>6fcaaee3-0f67-4096-af99-2ba582122eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulldog'])[1]/following::a[1]</value>
      <webElementGuid>716745c2-9b42-42be-ab2b-a866229039a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K9-BD-01'])[1]/following::a[1]</value>
      <webElementGuid>cdf88d8d-701d-40fa-acd8-1eaf0429ae84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poodle'])[1]/preceding::a[1]</value>
      <webElementGuid>645f2d25-8a0b-4777-b8d1-01ce76747edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K9-DL-01'])[1]/preceding::a[1]</value>
      <webElementGuid>ffb3bfea-116e-41c5-bded-eaa497444b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='K9-PO-02']/parent::*</value>
      <webElementGuid>dc868c41-f7c0-459c-b67f-13225c3d7e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/actions/Catalog.action?viewProduct=&amp;productId=K9-PO-02')]</value>
      <webElementGuid>e503f3f0-6dc5-46f5-9b07-1805dad747e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/a</value>
      <webElementGuid>7460fd56-e5c6-4ed0-8336-20888ef9f84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/actions/Catalog.action?viewProduct=&amp;productId=K9-PO-02' and (text() = 'K9-PO-02' or . = 'K9-PO-02')]</value>
      <webElementGuid>ea7930da-04c7-476e-afde-016f4d2dcb8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
