<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_VisaMasterCardAmerican Express</name>
   <tag></tag>
   <elementGuidId>a004dad1-0238-45e0-ab4f-3f9dbb405f66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;order.cardType&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='order.cardType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8283cd94-b559-47c0-b299-36bf5f13e5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order.cardType</value>
      <webElementGuid>9b3f28ce-1fb5-46f7-9f85-f7f9320fc27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				VisaMasterCardAmerican Express
			</value>
      <webElementGuid>92008063-688b-4ade-9d04-395551cf3836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[1]/tbody[1]/tr[2]/td[2]/select[1]</value>
      <webElementGuid>ee87d0af-2ded-4891-9d77-594ced801e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='order.cardType']</value>
      <webElementGuid>c808d82e-529a-480e-b6e0-090495537553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>28924268-09a7-4147-9168-6519707d1449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Type:'])[1]/following::select[1]</value>
      <webElementGuid>379ec4e7-19c0-44f4-858d-253b3e136214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Details'])[1]/following::select[1]</value>
      <webElementGuid>9f5b2cca-d53a-4363-9ac6-a29aadc9cd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number:'])[1]/preceding::select[1]</value>
      <webElementGuid>23af2348-a462-4e7c-951e-ce8b44a4c32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>784ba3c2-982a-498f-96b4-3245731b0da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'order.cardType' and (text() = '
				VisaMasterCardAmerican Express
			' or . = '
				VisaMasterCardAmerican Express
			')]</value>
      <webElementGuid>5baa3f5e-8049-47b6-944c-d3fd95f1e3f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
