<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiry Date (MMYYYY)_order.expiryDate</name>
   <tag></tag>
   <elementGuidId>899816d2-2ef9-4783-9b64-dcacaabe20ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;order.expiryDate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='order.expiryDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;order\.expiryDate&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e13af418-695f-415e-887c-0e1b864ed9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order.expiryDate</value>
      <webElementGuid>0b57d2b1-fdb1-41e1-9272-60f2fe4787de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e9a7719-7b52-404f-a168-0a399ced5503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12/03</value>
      <webElementGuid>c9b8b418-50cc-46b2-a5b3-f2c67094ae9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[1]/tbody[1]/tr[4]/td[2]/input[1]</value>
      <webElementGuid>8a792e91-4416-41f7-a1da-0794f3337012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='order.expiryDate']</value>
      <webElementGuid>2dc499e4-2fce-4ac8-9c7b-50fe7f8bf453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>a95d142c-3d35-4d18-a870-c6c7b0a76477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>77c5ff68-dd8e-40b4-b19f-9112a7d0db54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'order.expiryDate' and @type = 'text']</value>
      <webElementGuid>80a16e08-7f23-4e19-bd55-7deab96e87dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
